apiVersion: v1
kind: Service
metadata:
  name: nsd
  labels:
    app: dns-server
    component: nsd
spec:
  selector:
    app: dns-server
    component: nsd
  ports:
    - name: nsd-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: nsd-udp
      protocol: UDP
      port: 53
      targetPort: 53
  # type: ClusterIP
