apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsd
spec:
  selector:
    matchLabels:
      app: dns-server
      component: nsd
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-server
        component: nsd
    spec:
      containers:
        - name: nsd
          image: publicarray/nsd
          # command: ["/entrypoint.sh"]
          ports:
            - name: nsd
              containerPort: 53
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
      restartPolicy: Always
